server:
  port: 8080

spring:
  application:
    name: bajaj-finserv-qualifier-task

logging:
  level:
    com.bajajfinservhealth.qualifiertask: INFO
    org.springframework.web.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/qualifier-task.log